plugin 'cocoapods-fix-react-native'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '8.0'

target 'xoxo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for xoxo
  #pod 'Fabric'
  #pod 'Crashlytics'

# Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'

  #pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'xoxoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'xoxo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for xoxo-tvOS

  target 'xoxo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
